#include <ros/ros.h>
#include <image_transport/image_transport.h>
#include <cv_bridge/cv_bridge.h>
#include <sensor_msgs/image_encodings.h>
#include <opencv2/imgproc/imgproc.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/opencv.hpp>
#include <QDebug>
#include <QTime>
#include <math.h>
#include <QObject>
#include <vector>
#include <fstream>
#include <iostream>
#include <string>
#include <string.h>
#include <qmath.h>
#include <zbar.h>
#include "Headers/WhiteDetector.h"
#include "Headers/ProgramHandeler.h"
#include "Headers/inverter.h"
#include "Headers/LineEquations.h"
#include <line_connector2/my_msg.h>
#include <line_connector2/qr_msg.h>
