set(_CATKIN_CURRENT_PACKAGE "window_pkg")
set(window_pkg_VERSION "0.0.0")
set(window_pkg_MAINTAINER "alireza <alireza@todo.todo>")
set(window_pkg_PACKAGE_FORMAT "2")
set(window_pkg_BUILD_DEPENDS "roscpp" "rospy" "message_generation")
set(window_pkg_BUILD_EXPORT_DEPENDS "roscpp" "rospy")
set(window_pkg_BUILDTOOL_DEPENDS "catkin")
set(window_pkg_BUILDTOOL_EXPORT_DEPENDS )
set(window_pkg_EXEC_DEPENDS "roscpp" "rospy" "message_runtime" "message_generation")
set(window_pkg_RUN_DEPENDS "roscpp" "rospy" "message_runtime" "message_generation")
set(window_pkg_TEST_DEPENDS )
set(window_pkg_DOC_DEPENDS )
set(window_pkg_DEPRECATED "")